apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: in-cluster
    namespace: apps
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    path: "nginx"
    repoURL: "https://github.com/invisibl-labs/labs-senthil"
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
